### ISSUE TITLE
QUESTION: could you pls suggest an approach for nodeJS also?

### ISSUE THREAD

**Issue by aragalie** [salrashid123/clam_av#1]
Appreciated the tutorial, super useful @salrashid123 ! 

Would you please be able to help guide me with a few pointers on how could I use your approach but with nodeJS-based Cloud Function + receiving server on the instance? I'm not versed at all in Go, and I would rather build a pipeline with something I know so I can maintain it fully...

I'm also looking at the instructions [here](https://cloud.google.com/solutions/automating-malware-scanning-for-documents-uploaded-to-cloud-storage), but can't figure out yet the security aspects...

I guess what i'm struggling to grasp is how would your ILB/Instance approach translate to their App Engine Flex, while keeping the entire networking aspect? The ILB side I understand is taking care of by the auto-scaling aspect of Flex right?

Any pointers and general concepts highly appreciated, and i'll take it from there.

many thanks!

**Comment by salrashid123** [comment]
i think in node you'd have to emit the data in a stream:
   https://www.npmjs.com/package/clamscan#scan_stream
(i can't attest to that library but that whast the first link i saw)

i'd suggest starting up a local clamav server, starting up a nodejs app that reads a candidate file and then sends it in as a stream to clamav.

---

As for Flex, the solution i have is different...i intentionally wanted to process the candidate files in truly isolated envionment w/o any servcie account or network access to any other system (except the clam signature file via NAT).  You could even run a clamav container on its own in the instance group i've got.

So in a way, the av scanning is in a more secure environment that would autoscale anyway (the instance group in my git repo scales w/ load).  see this line in the setup:

```
gcloud compute instance-groups managed set-autoscaling clam-central-ig \
    --max-num-replicas 3 \
    --target-load-balancing-utilization 0.6 \
    --cool-down-period 90 --zone=$ZONE
```

**Comment by aragalie** [comment]
Thanks a lot, appreciate your time and explanations.
